//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Surveys_Manager.Lang {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Surveys_Manager.Lang.Resource", typeof(Resource).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add &apos;Other&apos; as an answer choice.
        /// </summary>
        internal static string addOther {
            get {
                return ResourceManager.GetString("addOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Age.
        /// </summary>
        internal static string age {
            get {
                return ResourceManager.GetString("age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Age Between (20 - 30).
        /// </summary>
        internal static string agebetween20_30 {
            get {
                return ResourceManager.GetString("agebetween20_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Age Between (30 - 40).
        /// </summary>
        internal static string agebetween30_40 {
            get {
                return ResourceManager.GetString("agebetween30_40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Age Between (40 - 50).
        /// </summary>
        internal static string agebetween40_50 {
            get {
                return ResourceManager.GetString("agebetween40_50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algeria.
        /// </summary>
        internal static string Algeria {
            get {
                return ResourceManager.GetString("Algeria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer Choices.
        /// </summary>
        internal static string Answer_choices {
            get {
                return ResourceManager.GetString("Answer_choices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answered By :.
        /// </summary>
        internal static string AnsweredBy {
            get {
                return ResourceManager.GetString("AnsweredBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Answers :.
        /// </summary>
        internal static string answers {
            get {
                return ResourceManager.GetString("answers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Changes will be discarded.
        /// </summary>
        internal static string bodyMessage {
            get {
                return ResourceManager.GetString("bodyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Your Answers , You Will Not Be Able To Answer The Questions ....
        /// </summary>
        internal static string bodyMessageSave {
            get {
                return ResourceManager.GetString("bodyMessageSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are More Receive Surveys , didn&apos;t see them ....
        /// </summary>
        internal static string BodyreceiveSurvey {
            get {
                return ResourceManager.GetString("BodyreceiveSurvey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are More Responsed Shared Surveys , didn&apos;t see them ....
        /// </summary>
        internal static string BodyResponsedٍ_Sh_Surveys {
            get {
                return ResourceManager.GetString("BodyResponsedٍ_Sh_Surveys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyse.
        /// </summary>
        internal static string btnAnalyse {
            get {
                return ResourceManager.GetString("btnAnalyse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string btnCancelMessage {
            get {
                return ResourceManager.GetString("btnCancelMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string btnEdit {
            get {
                return ResourceManager.GetString("btnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string btnOkMessage {
            get {
                return ResourceManager.GetString("btnOkMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  By :.
        /// </summary>
        internal static string by {
            get {
                return ResourceManager.GetString("by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANCEL.
        /// </summary>
        internal static string cancel_cab {
            get {
                return ResourceManager.GetString("cancel_cab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Information Should be not empty ....
        /// </summary>
        internal static string check_inputsSignin1 {
            get {
                return ResourceManager.GetString("check_inputsSignin1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to length password  should be less than 8  ....
        /// </summary>
        internal static string check_inputsSignin2 {
            get {
                return ResourceManager.GetString("check_inputsSignin2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your inputs should be not contain character like &apos;~&apos;.
        /// </summary>
        internal static string check_inputsSignin3 {
            get {
                return ResourceManager.GetString("check_inputsSignin3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Email is incorrect ....
        /// </summary>
        internal static string check_inputsSignin4 {
            get {
                return ResourceManager.GetString("check_inputsSignin4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Your Email or Password ....
        /// </summary>
        internal static string check_inputsSignin5 {
            get {
                return ResourceManager.GetString("check_inputsSignin5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the confirm of your password is incorrect ....
        /// </summary>
        internal static string confirmPassword {
            get {
                return ResourceManager.GetString("confirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Country.
        /// </summary>
        internal static string country {
            get {
                return ResourceManager.GetString("country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE.
        /// </summary>
        internal static string create {
            get {
                return ResourceManager.GetString("create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Your Surveys.
        /// </summary>
        internal static string Create_Surveys {
            get {
                return ResourceManager.GetString("Create_Surveys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        internal static string created {
            get {
                return ResourceManager.GetString("created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Survey.
        /// </summary>
        internal static string createsurveybtn {
            get {
                return ResourceManager.GetString("createsurveybtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Survey Education.
        /// </summary>
        internal static string createSurveyEducation {
            get {
                return ResourceManager.GetString("createSurveyEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Survey Marketing.
        /// </summary>
        internal static string createSurveyMarketing {
            get {
                return ResourceManager.GetString("createSurveyMarketing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Survey Other.
        /// </summary>
        internal static string createSurveyOther {
            get {
                return ResourceManager.GetString("createSurveyOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Survey Sport.
        /// </summary>
        internal static string createSurveySport {
            get {
                return ResourceManager.GetString("createSurveySport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are You Sure ...... ?.
        /// </summary>
        internal static string dangerSignOut {
            get {
                return ResourceManager.GetString("dangerSignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Date Response.
        /// </summary>
        internal static string Date_signup {
            get {
                return ResourceManager.GetString("Date_signup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string deleteSurveytoolbar {
            get {
                return ResourceManager.GetString("deleteSurveytoolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleteing.
        /// </summary>
        internal static string deleting {
            get {
                return ResourceManager.GetString("deleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to SurveyManager - the world&apos;s leading.
        /// </summary>
        internal static string detailsCreate1 {
            get {
                return ResourceManager.GetString("detailsCreate1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to survey platform. Create your next survey and use the.
        /// </summary>
        internal static string detailsCreate2 {
            get {
                return ResourceManager.GetString("detailsCreate2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insiths to make better decisions..
        /// </summary>
        internal static string detailsCreate3 {
            get {
                return ResourceManager.GetString("detailsCreate3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete The Item Selected.
        /// </summary>
        internal static string DetailsDeleting {
            get {
                return ResourceManager.GetString("DetailsDeleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are You Sure To Delete .
        /// </summary>
        internal static string detailsMessageDeleteSurvey {
            get {
                return ResourceManager.GetString("detailsMessageDeleteSurvey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are You Sure To Share .
        /// </summary>
        internal static string detailsMessageShareSurvey {
            get {
                return ResourceManager.GetString("detailsMessageShareSurvey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Drop Down.
        /// </summary>
        internal static string DropDownQuestion {
            get {
                return ResourceManager.GetString("DropDownQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Egypt.
        /// </summary>
        internal static string Egypt {
            get {
                return ResourceManager.GetString("Egypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The End Date : .
        /// </summary>
        internal static string endDate {
            get {
                return ResourceManager.GetString("endDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Answer Choice.
        /// </summary>
        internal static string Enter_A_Choice {
            get {
                return ResourceManager.GetString("Enter_A_Choice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search By Name or Email ....
        /// </summary>
        internal static string entrySearch {
            get {
                return ResourceManager.GetString("entrySearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string filter {
            get {
                return ResourceManager.GetString("filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter By :.
        /// </summary>
        internal static string filterBy {
            get {
                return ResourceManager.GetString("filterBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Welcome To Survey Manager.
        /// </summary>
        internal static string footer {
            get {
                return ResourceManager.GetString("footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go.
        /// </summary>
        internal static string go {
            get {
                return ResourceManager.GetString("go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the insights to make better decisions..
        /// </summary>
        internal static string insights {
            get {
                return ResourceManager.GetString("insights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iraq.
        /// </summary>
        internal static string Iraq {
            get {
                return ResourceManager.GetString("Iraq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jourdan.
        /// </summary>
        internal static string Jourdan {
            get {
                return ResourceManager.GetString("Jourdan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KSA.
        /// </summary>
        internal static string KSA {
            get {
                return ResourceManager.GetString("KSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Tapping &apos;Enter&apos; . You agree to our.
        /// </summary>
        internal static string last1 {
            get {
                return ResourceManager.GetString("last1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Terms Of Use&apos;.
        /// </summary>
        internal static string last2 {
            get {
                return ResourceManager.GetString("last2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        internal static string last3 {
            get {
                return ResourceManager.GetString("last3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobil App Privacy Statment.
        /// </summary>
        internal static string last4 {
            get {
                return ResourceManager.GetString("last4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and also agree.
        /// </summary>
        internal static string last5 {
            get {
                return ResourceManager.GetString("last5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to receving news and tips via email.
        /// </summary>
        internal static string last6 {
            get {
                return ResourceManager.GetString("last6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libya.
        /// </summary>
        internal static string Libya {
            get {
                return ResourceManager.GetString("Libya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mauritania.
        /// </summary>
        internal static string Mauritania {
            get {
                return ResourceManager.GetString("Mauritania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max :.
        /// </summary>
        internal static string maxValue {
            get {
                return ResourceManager.GetString("maxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string menutitle {
            get {
                return ResourceManager.GetString("menutitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min :.
        /// </summary>
        internal static string minValue {
            get {
                return ResourceManager.GetString("minValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moroco.
        /// </summary>
        internal static string Moroco {
            get {
                return ResourceManager.GetString("Moroco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Multiple Choice.
        /// </summary>
        internal static string MultibleQuestion {
            get {
                return ResourceManager.GetString("MultibleQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Questions in this Survey.
        /// </summary>
        internal static string no_questions {
            get {
                return ResourceManager.GetString("no_questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No  Accounts  Selected.
        /// </summary>
        internal static string NoAccountsSelected {
            get {
                return ResourceManager.GetString("NoAccountsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  You don&apos;t have any questions on this page yet..
        /// </summary>
        internal static string NoQuestions {
            get {
                return ResourceManager.GetString("NoQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Shared Surveys.
        /// </summary>
        internal static string noSharedSurveys {
            get {
                return ResourceManager.GetString("noSharedSurveys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Shared Surveys With You By Others Users.
        /// </summary>
        internal static string NoSurveys {
            get {
                return ResourceManager.GetString("NoSurveys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to isn&apos;t Connect With Local Server.
        /// </summary>
        internal static string notConnect {
            get {
                return ResourceManager.GetString("notConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t Have Any Account.
        /// </summary>
        internal static string NotFoundAccounts {
            get {
                return ResourceManager.GetString("NotFoundAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string other {
            get {
                return ResourceManager.GetString("other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Your Age.
        /// </summary>
        internal static string ph_age {
            get {
                return ResourceManager.GetString("ph_age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Your Country.
        /// </summary>
        internal static string ph_country {
            get {
                return ResourceManager.GetString("ph_country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Your Email.
        /// </summary>
        internal static string ph_email {
            get {
                return ResourceManager.GetString("ph_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a country.
        /// </summary>
        internal static string ph_enterAcountry {
            get {
                return ResourceManager.GetString("ph_enterAcountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Your Pasword.
        /// </summary>
        internal static string ph_password {
            get {
                return ResourceManager.GetString("ph_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Survey Description.
        /// </summary>
        internal static string ph_survey_descripation {
            get {
                return ResourceManager.GetString("ph_survey_descripation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Survey Title.
        /// </summary>
        internal static string ph_survey_title {
            get {
                return ResourceManager.GetString("ph_survey_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Question Text.
        /// </summary>
        internal static string ph_textQuestion {
            get {
                return ResourceManager.GetString("ph_textQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter User Name.
        /// </summary>
        internal static string ph_username {
            get {
                return ResourceManager.GetString("ph_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify Your Password.
        /// </summary>
        internal static string ph_Ver_password {
            get {
                return ResourceManager.GetString("ph_Ver_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question Text.
        /// </summary>
        internal static string question_text {
            get {
                return ResourceManager.GetString("question_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ratio Of The Answer :.
        /// </summary>
        internal static string RatioSlider {
            get {
                return ResourceManager.GetString("RatioSlider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ratio of Number of Participants.
        /// </summary>
        internal static string RatioText {
            get {
                return ResourceManager.GetString("RatioText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive Surveys.
        /// </summary>
        internal static string receivesurveys {
            get {
                return ResourceManager.GetString("receivesurveys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This question requires an answer..
        /// </summary>
        internal static string require_text {
            get {
                return ResourceManager.GetString("require_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsed Shared Surveys.
        /// </summary>
        internal static string responsedٍ_Sh_Surveys {
            get {
                return ResourceManager.GetString("responsedٍ_Sh_Surveys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Should Be Not Coontains &apos;~&apos; ..!!.
        /// </summary>
        internal static string rest_theTextQuestion {
            get {
                return ResourceManager.GetString("rest_theTextQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Is Required ..!!!.
        /// </summary>
        internal static string restTheQuestion {
            get {
                return ResourceManager.GetString("restTheQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAVE.
        /// </summary>
        internal static string save_cab {
            get {
                return ResourceManager.GetString("save_cab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string saveAddSurvey {
            get {
                return ResourceManager.GetString("saveAddSurvey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        internal static string selectAll {
            get {
                return ResourceManager.GetString("selectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Selected  .
        /// </summary>
        internal static string selected {
            get {
                return ResourceManager.GetString("selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        internal static string shareSurveytoolbar {
            get {
                return ResourceManager.GetString("shareSurveytoolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share With :.
        /// </summary>
        internal static string shareWith {
            get {
                return ResourceManager.GetString("shareWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sharing.
        /// </summary>
        internal static string sharing {
            get {
                return ResourceManager.GetString("sharing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Slider.
        /// </summary>
        internal static string sliderQuestion {
            get {
                return ResourceManager.GetString("sliderQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Start Date :.
        /// </summary>
        internal static string startDate {
            get {
                return ResourceManager.GetString("startDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Survey .
        /// </summary>
        internal static string survey {
            get {
                return ResourceManager.GetString("survey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syria.
        /// </summary>
        internal static string Syria {
            get {
                return ResourceManager.GetString("Syria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        internal static string textEnterSignup {
            get {
                return ResourceManager.GetString("textEnterSignup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Text Question.
        /// </summary>
        internal static string textQuestion {
            get {
                return ResourceManager.GetString("textQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        internal static string textSignin {
            get {
                return ResourceManager.GetString("textSignin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        internal static string textSignup {
            get {
                return ResourceManager.GetString("textSignup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Question .
        /// </summary>
        internal static string the_question {
            get {
                return ResourceManager.GetString("the_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This By :.
        /// </summary>
        internal static string this_By {
            get {
                return ResourceManager.GetString("this_By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                 Account.
        /// </summary>
        internal static string titleAccount {
            get {
                return ResourceManager.GetString("titleAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string titleDetails {
            get {
                return ResourceManager.GetString("titleDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education.
        /// </summary>
        internal static string titleEducation {
            get {
                return ResourceManager.GetString("titleEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketing.
        /// </summary>
        internal static string titleMarketing {
            get {
                return ResourceManager.GetString("titleMarketing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string titlemaster1 {
            get {
                return ResourceManager.GetString("titlemaster1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string titlemaster2 {
            get {
                return ResourceManager.GetString("titlemaster2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About us.
        /// </summary>
        internal static string titlemaster3 {
            get {
                return ResourceManager.GetString("titlemaster3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared Surveys.
        /// </summary>
        internal static string titlemaster4 {
            get {
                return ResourceManager.GetString("titlemaster4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received Surveys.
        /// </summary>
        internal static string titlemaster5 {
            get {
                return ResourceManager.GetString("titlemaster5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        internal static string titlemaster6 {
            get {
                return ResourceManager.GetString("titlemaster6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are You Sure ?.
        /// </summary>
        internal static string titleMessage {
            get {
                return ResourceManager.GetString("titleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        internal static string titleSignin {
            get {
                return ResourceManager.GetString("titleSignin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        internal static string titleSignup {
            get {
                return ResourceManager.GetString("titleSignup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sport.
        /// </summary>
        internal static string titleSport {
            get {
                return ResourceManager.GetString("titleSport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Survey.
        /// </summary>
        internal static string toolbarsurvey {
            get {
                return ResourceManager.GetString("toolbarsurvey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tunisia.
        /// </summary>
        internal static string Tunisia {
            get {
                return ResourceManager.GetString("Tunisia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single-select (Radio buttons).
        /// </summary>
        internal static string typePickerMulti_1 {
            get {
                return ResourceManager.GetString("typePickerMulti_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi-select (Check Boxs).
        /// </summary>
        internal static string typePickerMulti_2 {
            get {
                return ResourceManager.GetString("typePickerMulti_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UIA.
        /// </summary>
        internal static string UIA {
            get {
                return ResourceManager.GetString("UIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   UnSelected   .
        /// </summary>
        internal static string unSelected {
            get {
                return ResourceManager.GetString("unSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USA.
        /// </summary>
        internal static string USA {
            get {
                return ResourceManager.GetString("USA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        internal static string userName {
            get {
                return ResourceManager.GetString("userName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to there are same UserName or Email ....
        /// </summary>
        internal static string username_same_email {
            get {
                return ResourceManager.GetString("username_same_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Details.
        /// </summary>
        internal static string view_details {
            get {
                return ResourceManager.GetString("view_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome!.
        /// </summary>
        internal static string welcome {
            get {
                return ResourceManager.GetString("welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Your Question :.
        /// </summary>
        internal static string yourQuestion {
            get {
                return ResourceManager.GetString("yourQuestion", resourceCulture);
            }
        }
    }
}
